name: 'Deploy Brewdis App'

on:
  push:
    branches:
      - azure
    #paths:
    #  - '.github/*'
    #  - 'brewdis-api/*'

jobs:
  configure_app:
    name: 'Brewdis App configurations'
    runs-on: ubuntu-latest

    env:
      RESOURCE_GROUP: brewdis-prod # customize this
      SPRING_CLOUD_SERVICE: brewdis-spring-cloud # customize this
      SPRING_CLOUD_APP: brewdis-storefront # customize this
      BREWDIS_JAR: brewdis-api/build/libs/brewdis-api-1.0.0-SNAPSHOT.jar

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Login with Key Vault SP
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_KEY_VAULT }}
    
    - name: Get Resource Group SP from Key Vault
      uses: Azure/get-keyvault-secrets@v1.0
      with:
        keyvault: "brewrediskv"
        secrets: "AZURE-CREDENTIALS-BREWREDIS-PROD"
      id: resourcegroupsecrets
    
    - name: Get Redis Secrets from Key Vault
      uses: Azure/get-keyvault-secrets@v1.0
      with:
        keyvault: "brewrediskv"
        secrets: "SPRING-REDIS-HOST,SPRING-REDIS-PASSWORD"
      id: redissecrets
      
    - name: Login with Service SP
      uses: azure/login@v1
      with:
        creds: ${{ steps.resourcegroupsecrets.outputs.AZURE-CREDENTIALS-BREWREDIS-PROD }}
    
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    
    - name: Gradle build
      run: |
        ./gradlew build
        
    - name: Install ASC AZ extension
      run: az extension add --name spring-cloud
   
    - name: Deploy with AZ CLI commands
      run: |
          az configure --defaults group=$RESOURCE_GROUP
          az configure --defaults spring-cloud=$SPRING_CLOUD_SERVICE
          az spring-cloud app deployment create -n default \
            --app $SPRING_CLOUD_APP \
            --skip-clone-settings \
            --memory 2 \
            --runtime-version Java_11 \
            --jvm-options='-Xms2048m -Xmx2048m'\
            --jar-path ${{ github.workspace }}/$BREWDIS_JAR
          az spring-cloud app set-deployment -d default -n $SPRING_CLOUD_APP
          
    # Balan: Add steps here required to finish deployment of app
    # - name: Connect_App
    #   run: az ...

    # - name: Deploy_App
    #   run: az spring-cloud app deploy
