name: 'Deploy Brewdis App'

on:
  push:
    branches:
      - azure

jobs:
  configure_app:
    name: 'Brewdis App configurations'
    runs-on: ubuntu-latest

    env:
      RESOURCE_GROUP: brewdis # customize this
      SPRING_CLOUD_SERVICE: brewdis-prod # customize this
      SPRING_CLOUD_APP: storefront # customize this
      BREWDIS_JAR: brewdis-api/build/libs/brewdis-api-1.0.0-SNAPSHOT.jar
      SPRING_REDIS_PORT: 10000
      STOMP_PORT: 80

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Login with Key Vault SP
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_KEY_VAULT }}
    
    - name: Get Resource Group SP from Key Vault
      uses: Azure/get-keyvault-secrets@v1.0
      with:
        keyvault: "brewrediskv"
        secrets: "AZURE-CREDENTIALS-BREWREDIS-PROD, SPRING-REDIS-HOST, SPRING-REDIS-PASSWORD"
      id: keyvaultaction

    - name: Login with Service SP
      uses: azure/login@v1
      with:
        creds: ${{ steps.keyvaultaction.outputs.AZURE-CREDENTIALS-BREWREDIS-PROD }}
    
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    
    - name: Gradle build
      run: |
        ./gradlew build
        
    - name: Install ASC AZ extension
      run: az extension add --name spring-cloud
   
    - name: Deploy with AZ CLI commands
      run: |
          az spring-cloud app deploy \
            -s $SPRING_CLOUD_SERVICE \
            -g $RESOURCE_GROUP \
            --name $SPRING_CLOUD_APP \
            --jvm-options='-Xms2048m -Xmx2048m'\
            --jar-path ${{ github.workspace }}/$BREWDIS_JAR \
            --env SPRING_REDIS_HOST=${{ steps.keyvaultaction.outputs.SPRING-REDIS-HOST }} \
              SPRING_REDIS_PASSWORD=${{ steps.keyvaultaction.outputs.SPRING-REDIS-PASSWORD }} \
              SPRING_REDIS_PORT=$SPRING_REDIS_PORT \
              STOMP_HOST=${SPRING_CLOUD_SERVICE}-${SPRING_CLOUD_APP}.azuremicroservices.io \
              STOMP_PORT=$STOMP_PORT
